services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: parbatya
      POSTGRES_PASSWORD: parbatya
      POSTGRES_DB: parbatya
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
volumes:
  pgdata:
